### ISSUE TITLE
SecOC key checksum verification failed

### ISSUE THREAD

**Issue by pzh200707** [I-CAN-hack/secoc#6]
https://discord.com/channels/469524606043160576/905950538816978974/1239059542944518194

Car model: Toyota Corolla Cross 2022

I followed instructions by share-and-enjoy
https://discord.com/channels/469524606043160576/1238136715399397376
Commented out line 77 and 92 in extract_keys.py
The script ran successfully but reports "SecOC key checksum verification failed"
![image](https://github.com/I-CAN-hack/secoc/assets/26104496/ddd7ec0e-eb51-4055-9e61-b6d02d3908ba)
.bin file attached and I don't see any log uploaded to comma connect during the test.
https://drive.google.com/file/d/16J7VPehg6yO056HhDeDp48uz92AmkysD/view?usp=sharing
Is there any solution for this situation?

I have also tried secoc-while-loop
check_key_with_route.py → permission denied
![image](https://github.com/I-CAN-hack/secoc/assets/26104496/688a00b9-8d3d-4c33-a8e9-cd2a07047795)
extract_keys.py → it caused Power Steering Malfunction Steering Power Low warning which resolved after restart the car.

Thanks,

**Comment by pzh200707** [comment]
After commented out checksum verification. I got result below

comma@comma-4c6707ab:/data/openpilot/secoc$ ./extract_keys.py
Getting application versions...
 - APPLICATION_SOFTWARE_IDENTIFICATION (application) b'\x018965B1613000\x00\x00\x00\x00'
 - APPLICATION_SOFTWARE_IDENTIFICATION (bootloader)  b'\x02!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'

Security Access...
 - SEED: 582728d04cda23ad4de0f7ed82f3192c
 - KEY: a3c73a2be7664f7630b7dd0dfe0ca21e
 - Key OK!

Preparing to upload payload...
 - Write data by identifier 0x201 00000000000000000000000000000000
 - Write data by identifier 0x202 00000000000000000000000000000000

Upload payload...
 - Request download
 - Transfer data 0
 - Transfer data 1
 - Transfer data 2
 - Transfer data 3

Verify payload...
 - Routine control 0x10f0 OK!

Trigger payload...

Dumping keys...
100%|██████████████████████████████████████| 448/448 [00:00<00:00, 18452.80it/s]
SecOC key checksum verification failed!

ECU_MASTER_KEY    00000100000000000000010000000000
SecOC Key (KEY_4) 00000100000000000000010000000000

Failed to write SecOCKey param

**Comment by pzh200707** [comment]
Issue closed. Checked with author and no valid key is extracted. The key may be stored at HSM.

**Comment by a994862495** [comment]
Mine is also the 2022 Corolla Cross, but in China it's called the Corolla Ruifang. It's equipped with either TSS 2.0 or 2.5, but even after configuring all Toyota models, I still couldn't communicate with the ECU.
